apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mad1011/query-exporter-app:frontend-42
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://10.208.182.131:30081/api/v1"
            - name: REACT_APP_ADMIN_API_BASE_URL
              value: "http://10.208.182.131:30081/api/admin"
            - name: REACT_APP_API_AUTHENTICATE_BASE_URL
              value: "http://10.208.182.131:30081/api/auth"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
